# Generated by Django 2.1 on 2019-02-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_auto_20190128_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
